apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-ai.fullname" . }}
  labels:
    {{- include "devops-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: main
      protocol: TCP
    {{- if .Values.dashboard.enabled }}
    - name: dashboard
      port: {{ .Values.dashboard.port }}
      targetPort: dashboard
      protocol: TCP
    {{- end }}
  selector:
    {{- include "devops-ai.selectorLabels" . | nindent 4 }}
